// Default venues database - lista completa de venues portugueses
export interface DefaultVenue {
  id: string;
  name: string;
  city?: string;
  capacity?: string | number;
  address?: string;
  responsible?: string;
  phone?: string;
  email?: string;
  website?: string;
  equipment?: string;
  agreement?: string;
  notes?: string;
  source?: string;
}

export const DEFAULT_VENUES: DefaultVenue[] = [
  {
    id: "1",
    name: "Galeria Zé dos Bois (ZDB)",
    city: "Lisboa",
    capacity: "30-80 (confirmar)",
    address: "Rua da Barroca nº59, 1200-047 Lisboa",
    responsible: "",
    phone: "+351 21 343 02 05",
    email: "reservas@zedosbois.org",
    website: "https://zedosbois.org/",
    equipment: "PA disponível (confirmar rider)",
    agreement: "A negociar (bilheteira / bar split)",
    notes: "Espaço cultural com programação regular; confirmar lotação da sala específica.",
    source: "cite"
  },
  {
    id: "2",
    name: "Camones - Artes Bar",
    city: "Lisboa (Graça)",
    capacity: "30-60 (confirmar)",
    address: "Graça, Lisboa (ver site/IG)",
    responsible: "",
    phone: "(reservas via Instagram / FB)",
    email: "(ver Instagram/Facebook)",
    website: "https://www.instagram.com/camonesartesbar/",
    equipment: "PA / som house (confirmar)",
    agreement: "Normalmente bar split / bilheteira local (confirmar)",
    notes: "Local intimista com programação regular de concertos e open-mic.",
    source: "cite"
  },
  {
    id: "3",
    name: "B.O.T.A (Base Organizada da Toca das Artes)",
    city: "Lisboa (Anjos)",
    capacity: "30-70 (confirmar)",
    address: "Largo de Santa Bárbara, 3D, 1150-287 Lisboa",
    responsible: "",
    phone: "913 450 743",
    email: "(ver site/contactos)",
    website: "https://www.botaanjos.com/",
    equipment: "PA / infra cultural (confirmar rider)",
    agreement: "A negociar (frequentemente bilheteira / consumo)",
    notes: "Espaço multidisciplinar, boa opção para shows intimistas.",
    source: "cite"
  },
  {
    id: "4",
    name: "RCA Club",
    city: "Lisboa (Alvalade)",
    capacity: "30-100 (confirmar)",
    address: "Rua João Saraiva, nº18, Alvalade, Lisboa",
    responsible: "",
    phone: "(ver Facebook)",
    email: "(ver Facebook/contactos)",
    website: "https://www.rcaclub.com/",
    equipment: "PA e backline (club) - confirmar rider",
    agreement: "Club split / bilheteira (negociável)",
    notes: "Clube de rock com programação de concertos; boa opção para público alternativo.",
    source: "cite"
  },
  {
    id: "5",
    name: "DAMAS - Bar & Sala de Concertos",
    city: "Lisboa (Graça)",
    capacity: "30-70 (confirmar)",
    address: "Rua da Voz do Operário 60, Graça, Lisboa",
    responsible: "",
    phone: "351 912 162 249",
    email: "damasreservas@gmail.com",
    website: "https://www.instagram.com/damas.lisboa/",
    equipment: "PA / setup para bandas e showcases (confirmar)",
    agreement: "Consumo + bilheteira / bar split habitual",
    notes: "Restaurante-bar com palco; ideal para shows intimistas e público 30-50.",
    source: "cite"
  },
  {
    id: "6",
    name: "Maus Hábitos",
    city: "Porto",
    capacity: "40-120 (confirmar sala específica)",
    address: "Rua Passos Manuel 178, 4º, 4000-382 Porto",
    responsible: "",
    phone: "351 937 202 918",
    email: "geral@maushabitos.com / viciosdemesa@maushabitos.com",
    website: "https://www.maushabitos.com/",
    equipment: "Infra para concertos; PA disponível (confirmar rider)",
    agreement: "Bilheteira / contrato por evento (negociável)",
    notes: "Espaço cultural com historial de concertos; ideal para shows independentes.",
    source: "cite"
  },
  {
    id: "7",
    name: "Hot Five Jazz & Blues Club",
    city: "Porto",
    capacity: "30-60 (confirmar)",
    address: "Rua Guerra Junqueiro, nº495, 4150-098 Porto",
    responsible: "",
    phone: "(ver site)",
    email: "(ver site/contactos)",
    website: "https://hotfive.pt/",
    equipment: "PA adequado para jazz/blues - confirmar rider",
    agreement: "Bilheteira / consumação (negociável)",
    notes: "Clube especialista em jazz/blues, sessões regulares e jam nights.",
    source: "cite"
  },
  {
    id: "8",
    name: "M.Ou.Co (Hotel & música)",
    city: "Porto (Bonfim)",
    capacity: "30-80 (confirmar)",
    address: "Rua de Frei Heitor Pinto 67, Porto",
    responsible: "",
    phone: "(ver site)",
    email: "(ver site)",
    website: "(hotel / espaços privados)",
    equipment: "Espaço com infra para música (confirmar)",
    agreement: "Eventos privados / programações do hotel (negociável)",
    notes: "Hotel temático de música — opções de salas intimistas para showcases.",
    source: "cite"
  },
  {
    id: "9",
    name: "TEXAS Club Leiria",
    city: "Leiria (Barreiros/Amor)",
    capacity: "40-200 (confirmar sala)",
    address: "R. Padre Margalhau / R. Padre Joaquim G. Margalhau nº 1390, Amor/Barreiros, Leiria",
    responsible: "",
    phone: "(ver Facebook / Instagram / site)",
    email: "(ver redes sociais)",
    website: "https://www.facebook.com/texasleiria/",
    equipment: "Sala de espetáculos; PA (confirmar rider)",
    agreement: "Venda de bilhetes / promotoria local (negociável)",
    notes: "Histórico de concertos desde 1992; boa opção regional.",
    source: "cite"
  },
  {
    id: "10",
    name: "Mulligan's Irish Bar",
    city: "Leiria (Centro)",
    capacity: "30-80 (confirmar)",
    address: "Largo Alexandre Herculano, 2, 2410-083 Leiria",
    responsible: "",
    phone: "351 244 204 741",
    email: "(ver Facebook/site)",
    website: "http://www.mulligans.pt/ (FB/IG)",
    equipment: "PA pequeno possível; ambiente pub com música ao vivo",
    agreement: "Bar split / entrada (negociável)",
    notes: "Pub com tradição de música ao vivo — bom para shows intimistas.",
    source: "cite"
  },
  {
    id: "11",
    name: "Á Capella (Fado de Coimbra)",
    city: "Coimbra",
    capacity: "30-60 (confirmar)",
    address: "Rua Corpo de Deus - Largo da Vitória, Coimbra",
    responsible: "",
    phone: "351 239 833 985",
    email: "mail.acapella@gmail.com",
    website: "https://coimbramusica.com/ / Facebook aCapella",
    equipment: "Som e palco pequeno (confirmar)",
    agreement: "Bilheteira / jantares com espetáculo (negociável)",
    notes: "Capela convertida em espaço musical — acústica favorável para intimista.",
    source: "cite"
  },
  {
    id: "12",
    name: "Teatro Lethes",
    city: "Faro (extra city)",
    capacity: "50-200 (confirmar - teatro)",
    address: "Rua de Portugal 58, 8000-281 Faro",
    responsible: "",
    phone: "351 289 878 908",
    email: "geral@actateatro.org.pt",
    website: "https://teatrolethes.com/",
    equipment: "Infra teatral completa; PA a confirmar",
    agreement: "Venda bilhetes via teatro (negociável)",
    notes: "Teatro municipal histórico — possível para noites acústicas, confirmar lotação mínima.",
    source: "cite"
  },
  {
    id: "13",
    name: "Salpoente (Aveiro)",
    city: "Aveiro (extra city)",
    capacity: "30-80 (confirmar)",
    address: "Canal de São Roque, nº 82/83, 3800-256 Aveiro",
    responsible: "",
    phone: "+351 234 382 674, +351 915 138 619",
    email: "salpoente@salpoente.pt",
    website: "https://salpoente.pt/",
    equipment: "Espaço restaurante com possibilidade de música ao vivo (confirmar PA)",
    agreement: "Eventos privados / jantar + bilheteira (negociável)",
    notes: "Restaurante com espaço histórico — bom para showcases íntimos com jantar.",
    source: "cite"
  },
  {
    id: "14",
    name: "Teatro Viriato",
    city: "Viseu (extra city)",
    capacity: "(teatro - confirmar sala pequena para 30-50)",
    address: "L. Mouzinho de Albuquerque, Viriato / Teatro Municipal Viriato, Viseu",
    responsible: "",
    phone: "351 232 480 110",
    email: "(ver site)",
    website: "https://www.teatroviriato.com/",
    equipment: "Infra completa (teatro) - confirmar sala pequena e PA",
    agreement: "Venda bilhetes via bilheteira (negociável)",
    notes: "Teatro municipal com várias salas — confirmar qual aluga para shows de 30-50 pessoas.",
    source: "cite"
  },
  {
    id: "15",
    name: "Barreirinha Bar Café",
    city: "Funchal (extra city)",
    capacity: "30-80 (confirmar)",
    address: "Largo do Socorro, nº1, 9060-305 Funchal, Madeira",
    responsible: "",
    phone: "(ver Facebook/IG)",
    email: "(ver redes sociais)",
    website: "https://www.instagram.com/barreirinhabarcafe/",
    equipment: "PA pequeno possível; esplanada para música ao vivo",
    agreement: "Bar split / consumo (negociável)",
    notes: "Bar com programação musical noturna; boa visibilidade turística.",
    source: "cite"
  },
  {
    id: "16",
    name: "Teatro Micaelense",
    city: "Ponta Delgada (extra city)",
    capacity: "(teatro - verificar sala pequena)",
    address: "Largo de São João, 9500-106 Ponta Delgada, S. Miguel, Açores",
    responsible: "",
    phone: "351 296 308 340",
    email: "info@teatromicaelense.pt / bilheteira@teatromicaelense.pt",
    website: "https://www.teatromicaelense.pt/",
    equipment: "Infra completa; bilheteira e técnica do teatro",
    agreement: "Venda através da bilheteira; negociar split com teatro",
    notes: "Centro cultural principal nos Açores — bom para datas específicas; confirmar sala adequada para 30-50.",
    source: "cite"
  },
  {
    id: "17",
    name: "Titanic Sur Mer",
    city: "Lisboa (Cais do Sodré)",
    capacity: "(confirmar)",
    address: "Cais da Ribeira Nova, Armazém B, Cais do Sodré, Lisboa, Portugal",
    responsible: "",
    phone: "",
    email: "info.titanicsurmer@gmail.com",
    website: "",
    equipment: "PA / palco (confirmar)",
    agreement: "A negociar (bilheteira/bar split — confirmar)",
    notes: "Sala de eventos no Cais do Sodré; horário a confirmar.",
    source: "user"
  },
  {
    id: "18",
    name: "Tokyo Lisboa",
    city: "Lisboa (Cais do Sodré)",
    capacity: "265 (lotação máxima)",
    address: "Cais Gás 1, 1200-109 Lisboa",
    responsible: "",
    phone: "213 462 265",
    email: "tokyo@tokyo.com.pt",
    website: "",
    equipment: "Club; PA (confirmar rider)",
    agreement: "A negociar (confirmar política)",
    notes: "Horário: Quarta à Sábado, 22h–06h. SPA: €87,00 (lucro por show — a confirmar).",
    source: "user"
  },
  {
    id: "19",
    name: "Music Box",
    city: "Lisboa (Pink Street, Cais do Sodré)",
    capacity: "280 (lotação máxima)",
    address: "R. Nova do Carvalho 24, 1200-019 Lisboa",
    responsible: "Cultural Trend Lisbon",
    phone: "213 430 107",
    email: "office@musicboxlisboa.com",
    website: "",
    equipment: "Sala de concertos; PA e luz (confirmar)",
    agreement: "A negociar (contrato/bilheteira)",
    notes: "NIF: 507 589 939. SPA: €87,00 (lucro por show — a confirmar).",
    source: "user"
  },
  {
    id: "20",
    name: "Palácio do Grillo",
    city: "(Lisboa — a confirmar)",
    capacity: "(confirmar)",
    address: "",
    responsible: "",
    phone: "",
    email: "palaciogriloeventos@gmail.com",
    website: "",
    equipment: "(confirmar)",
    agreement: "(confirmar)",
    notes: "Espaço histórico para eventos; detalhes a confirmar.",
    source: "user"
  },
  {
    id: "21",
    name: "Cargo 111",
    city: "(Lisboa — a confirmar)",
    capacity: "(confirmar)",
    address: "",
    responsible: "",
    phone: "",
    email: "Cargo111ba@gmail.com",
    website: "",
    equipment: "(confirmar)",
    agreement: "(confirmar)",
    notes: "Bar/sala de eventos; detalhes a confirmar.",
    source: "user"
  },
  {
    id: "22",
    name: "Teatro Sá de Miranda",
    city: "Viana do Castelo",
    capacity: "(teatro - confirmar sala pequena para 30-80)",
    address: "Rua Sá de Miranda, 4900-529 Viana do Castelo",
    responsible: "",
    phone: "(ver site)",
    email: "(ver site/contactos)",
    website: "",
    equipment: "Infra teatral completa; PA a confirmar",
    agreement: "Venda bilhetes via teatro / parceria institucional",
    notes: "Teatro histórico da cidade — espaço ideal para datas culturais e circuitos alternativos.",
    source: "CAE90040"
  },
  {
    id: "23",
    name: "Teatro Aveirense",
    city: "Aveiro",
    capacity: "(teatro - confirmar sala alternativa para showcases)",
    address: "Rua Belém Pará, 3810-066 Aveiro",
    responsible: "",
    phone: "(ver site)",
    email: "(ver site/contactos)",
    website: "https://www.teatroaveirense.pt/",
    equipment: "Infra completa (som/luz), staff técnico",
    agreement: "Venda bilheteira via teatro; contratual / parceria",
    notes: "Equipamento municipal — ideal para programação estruturada.",
    source: "CAE90040"
  },
  {
    id: "24",
    name: "Pavilhão do Arade",
    city: "Lagoa (Algarve)",
    capacity: "(multiusos - confirmar sala pequena para showcases)",
    address: "Urb. Passagem, 8400-611 Parchal",
    responsible: "",
    phone: "(ver site)",
    email: "(ver site)",
    website: "",
    equipment: "Infraestrutura para congressos e espetáculos",
    agreement: "A negociar (contrato de espaço / bilheteira)",
    notes: "Centro de congressos e espetáculos regional — boa alternativa no Algarve.",
    source: "CAE90040"
  },
  {
    id: "25",
    name: "Centro de Bridge de Lisboa S.A",
    city: "Lisboa",
    capacity: "(confirmar salas para eventos culturais)",
    address: "Av. António Augusto de Aguiar, 163, 4ºE, 1050-014 Lisboa",
    responsible: "",
    phone: "(ver site)",
    email: "(ver site)",
    website: "",
    equipment: "A confirmar",
    agreement: "A negociar",
    notes: "Operador registado em CAE 90040 — possível espaço multiusos em Lisboa.",
    source: "CAE90040"
  },
  {
    id: "26",
    name: "Praça das Flores - Produção de Espectáculos, Lda.",
    city: "Lisboa",
    capacity: "(operador — confirmar espaços próprios ou gestão de salas)",
    address: "Rua Imprensa Nacional 36, 1250-126 Lisboa",
    responsible: "",
    phone: "",
    email: "",
    website: "",
    equipment: "(confirmar)",
    agreement: "(confirmar)",
    notes: "Produtora com CAE 90040 — possível parceira para co-produções ou aluguer de salas.",
    source: "CAE90040"
  },
  {
    id: "27",
    name: "Smart Events - Produção de Espectáculos e Organização de Eventos, Lda.",
    city: "Lisboa",
    capacity: "(operador — confirmar salas próprias ou eventos itinerantes)",
    address: "Av. Infante D. Henrique 333, 5º - 62, 1800-282 Lisboa",
    responsible: "",
    phone: "",
    email: "",
    website: "",
    equipment: "(confirmar)",
    agreement: "(confirmar)",
    notes: "Empresa especializada em eventos e espetáculos; potencial para parcerias e datas em circuito.",
    source: "CAE90040"
  },
  {
    id: "28",
    name: "Empresa Artística S.A",
    city: "Porto",
    capacity: "(confirmar espaços próprios ou gestão de salas)",
    address: "Rua Gonçalo Sampaio, Nº39, 6º, 4150-366 Porto",
    responsible: "",
    phone: "",
    email: "",
    website: "",
    equipment: "(confirmar)",
    agreement: "(confirmar)",
    notes: "Empresa de espetáculos sediada no Porto com CAE 90040 — possível contacto para produções.",
    source: "CAE90040"
  },
  {
    id: "29",
    name: "Casino Fundanense S.A",
    city: "Fundão",
    capacity: "(confirmar sala de espetáculos)",
    address: "Praça do Município, 6230-338 Fundão",
    responsible: "",
    phone: "",
    email: "",
    website: "",
    equipment: "A confirmar",
    agreement: "A negociar",
    notes: "Operador regional com CAE 90040 — potencial para circuitos no interior.",
    source: "CAE90040"
  },
  {
    id: "30",
    name: "Cul.tur - Empresa Municipal de Cultura e Turismo de Santarém, Eem",
    city: "Marvila, Santarém",
    capacity: "(confirmar)",
    address: "",
    responsible: "",
    phone: "",
    email: "",
    website: "",
    equipment: "(confirmar)",
    agreement: "(confirmar)",
    notes: "Empresa municipal de cultura e turismo — possível espaço/gestão de eventos.",
    source: "CAE90040/NIF:509477755"
  },
  {
    id: "31",
    name: "Agência Roque - Produções e Agenciamento de Espectáculos, Lda",
    city: "Portela, Loures",
    capacity: "(operador)",
    address: "",
    responsible: "",
    phone: "",
    email: "",
    website: "",
    equipment: "(confirmar)",
    agreement: "(confirmar)",
    notes: "Produtora e agenciamento de espetáculos — possível parceria para tours e eventos.",
    source: "NIF:502953713"
  },
  {
    id: "32",
    name: "Jovens Cantores de Lisboa - Animação Cultural, Crl",
    city: "Lisboa",
    capacity: "(confirmar)",
    address: "",
    responsible: "",
    phone: "",
    email: "",
    website: "",
    equipment: "(confirmar)",
    agreement: "(confirmar)",
    notes: "Associação cultural de animação musical — potencial para colaborações educativas e concertos.",
    source: "NIF:502918942"
  },
  {
    id: "33",
    name: "Promodel, Lda",
    city: "Alcabideche, Cascais",
    capacity: "(operador)",
    address: "",
    responsible: "",
    phone: "",
    email: "",
    website: "",
    equipment: "(confirmar)",
    agreement: "(confirmar)",
    notes: "Empresa de produção e eventos — possível parceiro para shows e logística.",
    source: "NIF:508915287"
  },
  {
    id: "34",
    name: "Eurobowling Imobiliária e Técnica, Lda",
    city: "São João de Lourosa, Viseu",
    capacity: "(confirmar)",
    address: "",
    responsible: "",
    phone: "",
    email: "",
    website: "",
    equipment: "(confirmar)",
    agreement: "(confirmar)",
    notes: "Empresa técnica com experiência em eventos — verificar disponibilidade de espaço e infra.",
    source: "NIF:502215780"
  },
  {
    id: "35",
    name: "Share Your Views Lda",
    city: "Lovelhe, Vila Nova de Cerveira",
    capacity: "(confirmar)",
    address: "",
    responsible: "",
    phone: "",
    email: "",
    website: "",
    equipment: "(confirmar)",
    agreement: "(confirmar)",
    notes: "Produtora/empresa de eventos — potencial para showcases ou eventos corporativos.",
    source: "NIF:508991889"
  },
  {
    id: "36",
    name: "Chaves Viva - Associação Promotora Para O Ensino e Divulgação das Artes e Ofícios da Região Flaviense",
    city: "Chaves, Vila Real",
    capacity: "(confirmar)",
    address: "",
    responsible: "",
    phone: "",
    email: "",
    website: "",
    equipment: "(confirmar)",
    agreement: "(confirmar)",
    notes: "Associação cultural — ideal para concertos educativos e atividades de difusão artística.",
    source: "NIF:509013740"
  },
  {
    id: "37",
    name: "Cinema Em Conversa - Cineclube da Maia",
    city: "Maia, Porto",
    capacity: "(sala de cinema / espaço cultural)",
    address: "",
    responsible: "",
    phone: "",
    email: "",
    website: "",
    equipment: "PA e projeção audiovisual (confirmar)",
    agreement: "(negociável)",
    notes: "Cineclube com programação cultural — possível para eventos híbridos ou showcases.",
    source: "NIF:509295401"
  },
  {
    id: "38",
    name: "Coniorquestra - Sociedade Musical, Lda",
    city: "Caldelas, Guimarães",
    capacity: "(confirmar)",
    address: "",
    responsible: "",
    phone: "",
    email: "",
    website: "",
    equipment: "(confirmar)",
    agreement: "(confirmar)",
    notes: "Sociedade musical — possível parceria para concertos e ensaios abertos.",
    source: "NIF:501484647"
  },
  {
    id: "39",
    name: "Jorge Miguel Rodrigues, Unipessoal Lda",
    city: "Pombeiro da Beira, Arganil",
    capacity: "(confirmar)",
    address: "",
    responsible: "",
    phone: "",
    email: "",
    website: "",
    equipment: "(confirmar)",
    agreement: "(confirmar)",
    notes: "Produtor/empresa de eventos locais — verificar lotação para shows intimistas.",
    source: "NIF:509767060"
  }
];



