// Base de dados inicial de venues de Portugal
// Este arquivo contém todas as venues fornecidas pelo utilizador

import { Venue } from "./venuesDb";

export const DEFAULT_VENUES: Omit<Venue, "id" | "createdAt" | "updatedAt">[] = [
  {
    name: "Galeria Zé dos Bois (ZDB)",
    city: "Lisboa",
    country: "Portugal",
    address: "Rua da Barroca nº59, 1200-047 Lisboa",
    capacity: "30-80 (confirmar)",
    contactPhone: "+351 21 343 02 05",
    contactEmail: "reservas@zedosbois.org",
    url: "https://zedosbois.org",
    equipment: "PA disponível (confirmar rider)",
    agreement: "A negociar (bilheteira / bar split)",
    notes: "Espaço cultural com programação regular; confirmar capacidade da sala específica.",
    region: "Sul",
    cae: "93290",
  },
  {
    name: "Camones - Artes Bar",
    city: "Lisboa",
    country: "Portugal",
    address: "Graça, Lisboa (ver site/IG)",
    capacity: "30-60 (confirmar)",
    contactPhone: "(reservas via Instagram / FB)",
    contactEmail: "(ver Instagram/Facebook)",
    equipment: "PA / som house (confirmar)",
    agreement: "Normalmente bar split / bilheteira local (confirmar)",
    notes: "Local intimista com programação regular de concertos e open-mic.",
    region: "Sul",
    cae: "56302",
  },
  {
    name: "B.O.T.A (Base Organizada da Toca das Artes)",
    city: "Lisboa",
    country: "Portugal",
    address: "Largo de Santa Bárbara, 3D, 1150-287 Lisboa",
    capacity: "30-70 (confirmar)",
    contactPhone: "913 450 743",
    equipment: "PA / infra cultural (confirmar rider)",
    agreement: "A negociar (frequentemente bilheteira / consumo)",
    notes: "Espaço multidisciplinar, boa opção para shows intimistas.",
    region: "Sul",
    cae: "93290",
  },
  {
    name: "RCA Club",
    city: "Lisboa",
    country: "Portugal",
    address: "Rua João Saraiva, nº18, Alvalade, Lisboa",
    capacity: "30-100 (confirmar)",
    contactPhone: "(ver Facebook)",
    contactEmail: "(ver Facebook/contactos)",
    equipment: "PA e backline (club) - confirmar rider",
    agreement: "Club split / bilheteira (negociável)",
    notes: "Clube de rock com programação de concertos; boa opção para público alternativo.",
    region: "Sul",
    cae: "56302",
  },
  {
    name: "DAMAS - Bar & Sala de Concertos",
    city: "Lisboa",
    country: "Portugal",
    address: "Rua da Voz do Operário 60, Graça, Lisboa",
    capacity: "30-70 (confirmar)",
    contactPhone: "351 912 162 249",
    contactEmail: "damasreservas@gmail.com",
    equipment: "PA / setup para bandas e showcases (confirmar)",
    agreement: "Consumo + bilheteira / bar split habitual",
    notes: "Restaurante-bar com palco; ideal para shows intimistas e público 30-50.",
    region: "Sul",
    cae: "56302",
  },
  {
    name: "Maus Hábitos",
    city: "Porto",
    country: "Portugal",
    address: "Rua Passos Manuel 178, 4º, 4000-382 Porto",
    capacity: "40-120 (confirmar sala específica)",
    contactPhone: "351 937 202 918",
    contactEmail: "geral@maushabitos.com / viciosdemesa@maushabitos.com",
    url: "https://maushabitos.com",
    equipment: "Infra para concertos; PA disponível (confirmar rider)",
    agreement: "Bilheteira / contrato por evento (negociável)",
    notes: "Espaço cultural com historial de concertos; ideal para shows independentes.",
    region: "Norte",
    cae: "93290",
  },
  {
    name: "Hot Five Jazz & Blues Club",
    city: "Porto",
    country: "Portugal",
    address: "Rua Guerra Junqueiro, nº495, 4150-098 Porto",
    capacity: "30-60 (confirmar)",
    equipment: "PA adequado para jazz/blues - confirmar rider",
    agreement: "Bilheteira / consumação (negociável)",
    notes: "Clube especialista em jazz/blues, sessões regulares e jam nights.",
    region: "Norte",
    cae: "56302",
  },
  {
    name: "M.Ou.Co (Hotel & música)",
    city: "Porto",
    country: "Portugal",
    address: "Rua de Frei Heitor Pinto 67, Porto",
    capacity: "30-80 (confirmar)",
    equipment: "Espaço com infra para música (confirmar)",
    agreement: "Eventos privados / programações do hotel (negociável)",
    notes: "Hotel temático de música — opções de salas intimistas para showcases.",
    region: "Norte",
    cae: "93293",
  },
  {
    name: "TEXAS Club Leiria",
    city: "Leiria",
    country: "Portugal",
    address: "R. Padre Margalhau / R. Padre Joaquim G. Margalhau nº 1390, Amor/Barreiros, Leiria",
    capacity: "40-200 (confirmar sala)",
    equipment: "Sala de espetáculos; PA (confirmar rider)",
    agreement: "Venda de bilhetes / promotoria local (negociável)",
    notes: "Histórico de concertos desde 1992; boa opção regional.",
    region: "Centro",
    cae: "90040",
  },
  {
    name: "Mulligan's Irish Bar",
    city: "Leiria",
    country: "Portugal",
    address: "Largo Alexandre Herculano, 2, 2410-083 Leiria",
    capacity: "30-80 (confirmar)",
    contactPhone: "351 244 204 741",
    equipment: "PA pequeno possível; ambiente pub com música ao vivo",
    agreement: "Bar split / entrada (negociável)",
    notes: "Pub com tradição de música ao vivo — bom para shows intimistas.",
    region: "Centro",
    cae: "56302",
  },
  {
    name: "Á Capella (Fado de Coimbra)",
    city: "Coimbra",
    country: "Portugal",
    address: "Rua Corpo de Deus - Largo da Vitória, Coimbra",
    capacity: "30-60 (confirmar)",
    contactPhone: "351 239 833 985",
    contactEmail: "mail.acapella@gmail.com",
    equipment: "Som e palco pequeno (confirmar)",
    agreement: "Bilheteira / jantares com espetáculo (negociável)",
    notes: "Capela convertida em espaço musical — acústica favorável para intimista.",
    region: "Centro",
    cae: "93290",
  },
  {
    name: "Teatro Lethes",
    city: "Faro",
    country: "Portugal",
    address: "Rua de Portugal 58, 8000-281 Faro",
    capacity: "50-200 (confirmar - teatro)",
    contactPhone: "351 289 878 908",
    contactEmail: "geral@actateatro.org.pt",
    equipment: "Infra teatral completa; PA a confirmar",
    agreement: "Venda bilhetes via teatro (negociável)",
    notes: "Teatro municipal histórico — possível para noites acústicas, confirmar capacidade mínima.",
    region: "Sul",
    cae: "90040",
  },
  {
    name: "Salpoente",
    city: "Aveiro",
    country: "Portugal",
    address: "Canal de São Roque, nº 82/83, 3800-256 Aveiro",
    capacity: "30-80 (confirmar)",
    contactPhone: "+351 234 382 674, +351 915 138 619",
    contactEmail: "salpoente@salpoente.pt",
    equipment: "Espaço restaurante com possibilidade de música ao vivo (confirmar PA)",
    agreement: "Eventos privados / jantar + bilheteira (negociável)",
    notes: "Restaurante com espaço histórico — bom para showcases íntimos com jantar.",
    region: "Centro",
    cae: "56302",
  },
  {
    name: "Teatro Viriato",
    city: "Viseu",
    country: "Portugal",
    address: "L. Mouzinho de Albuquerque, Viriato / Teatro Municipal Viriato, Viseu",
    capacity: "(teatro - confirmar sala pequena para 30-50)",
    contactPhone: "351 232 480 110",
    equipment: "Infra completa (teatro) - confirmar sala pequena e PA",
    agreement: "Venda bilhetes via bilheteira (negociável)",
    notes: "Teatro municipal com várias salas — confirmar qual aluga para shows de 30-50 pessoas.",
    region: "Centro",
    cae: "90040",
  },
  {
    name: "Barreirinha Bar Café",
    city: "Funchal",
    country: "Portugal",
    address: "Largo do Socorro, nº1, 9060-305 Funchal, Madeira",
    capacity: "30-80 (confirmar)",
    equipment: "PA pequeno possível; esplanada para música ao vivo",
    agreement: "Bar split / consumo (negociável)",
    notes: "Bar com programação musical noturna; boa visibilidade turística.",
    region: "Ilhas",
    cae: "56302",
  },
  {
    name: "Teatro Micaelense",
    city: "Ponta Delgada",
    country: "Portugal",
    address: "Largo de São João, 9500-106 Ponta Delgada, S. Miguel, Açores",
    capacity: "(teatro - verificar sala pequena)",
    contactPhone: "351 296 308 340",
    contactEmail: "info@teatromicaelense.pt / bilheteira@teatromicaelense.pt",
    equipment: "Infra completa; bilheteira e técnica do teatro",
    agreement: "Venda através da bilheteira; negociar split com teatro",
    notes: "Centro cultural principal nos Açores — bom para datas específicas; confirmar sala adequada para 30-50.",
    region: "Ilhas",
    cae: "90040",
  },
  {
    name: "Titanic Sur Mer",
    city: "Lisboa",
    country: "Portugal",
    address: "Cais da Ribeira Nova, Armazém B, Cais do Sodré, Lisboa, Portugal",
    contactEmail: "info.titanicsurmer@gmail.com",
    equipment: "PA / palco (confirmar)",
    agreement: "A negociar (bilheteira/bar split — confirmar)",
    notes: "Sala de eventos no Cais do Sodré; horário a confirmar.",
    region: "Sul",
    cae: "93290",
  },
  {
    name: "Tokyo Lisboa",
    city: "Lisboa",
    country: "Portugal",
    address: "Cais Gás 1, 1200-109 Lisboa",
    capacity: "265 (lotação máxima)",
    contactPhone: "213 462 265",
    contactEmail: "tokyo@tokyo.com.pt",
    equipment: "Club; PA (confirmar rider)",
    agreement: "A negociar (confirmar política)",
    notes: "Horário: Quarta à Sábado, 22h–06h. SPA: €87,00 (lucro por show — a confirmar).",
    region: "Sul",
    cae: "56302",
    spaNumber: "€87,00 (lucro por show — a confirmar)",
  },
  {
    name: "Music Box",
    city: "Lisboa",
    country: "Portugal",
    address: "R. Nova do Carvalho 24, 1200-019 Lisboa",
    capacity: "280 (lotação máxima)",
    contactPhone: "213 430 107",
    contactEmail: "office@musicboxlisboa.com",
    equipment: "Sala de concertos; PA e luz (confirmar)",
    agreement: "A negociar (contrato/bilheteira)",
    notes: "NIF: 507 589 939. SPA: €87,00 (lucro por show — a confirmar).",
    region: "Sul",
    cae: "90040",
    nif: "507 589 939",
    spaNumber: "€87,00 (lucro por show — a confirmar)",
  },
  {
    name: "Palácio do Grillo",
    city: "Lisboa",
    country: "Portugal",
    contactEmail: "palaciogriloeventos@gmail.com",
    notes: "Espaço histórico para eventos; detalhes a confirmar.",
    region: "Sul",
    cae: "93290",
  },
  {
    name: "Cargo 111",
    city: "Lisboa",
    country: "Portugal",
    contactEmail: "Cargo111ba@gmail.com",
    notes: "Bar/sala de eventos; detalhes a confirmar.",
    region: "Sul",
    cae: "93290",
  },
  {
    name: "Teatro Sá de Miranda",
    city: "Viana do Castelo",
    country: "Portugal",
    address: "Rua Sá de Miranda, 4900-529 Viana do Castelo",
    capacity: "(teatro - confirmar sala pequena para 30-80)",
    equipment: "Infra teatral completa; PA a confirmar",
    agreement: "Venda bilhetes via teatro / parceria institucional",
    notes: "Teatro histórico da cidade — espaço ideal para datas culturais e circuitos alternativos.",
    region: "Norte",
    cae: "90040",
  },
  {
    name: "Teatro Aveirense",
    city: "Aveiro",
    country: "Portugal",
    address: "Rua Belém Pará, 3810-066 Aveiro",
    equipment: "Infra completa (som/luz), staff técnico",
    agreement: "Venda bilheteira via teatro; contratual / parceria",
    notes: "Equipamento municipal — ideal para programação estruturada.",
    region: "Centro",
    cae: "90040",
  },
  {
    name: "Pavilhão do Arade",
    city: "Lagoa",
    country: "Portugal",
    address: "Urb. Passagem, 8400-611 Parchal",
    capacity: "(multiusos - confirmar sala pequena para showcases)",
    equipment: "Infraestrutura para congressos e espetáculos",
    agreement: "A negociar (contrato de espaço / bilheteira)",
    notes: "Centro de congressos e espetáculos regional — boa alternativa no Algarve.",
    region: "Sul",
    cae: "90040",
  },
  {
    name: "Centro de Bridge de Lisboa S.A",
    city: "Lisboa",
    country: "Portugal",
    address: "Av. António Augusto de Aguiar, 163, 4ºE, 1050-014 Lisboa",
    notes: "Operador registado em CAE 90040 — possível espaço multiusos em Lisboa.",
    region: "Sul",
    cae: "90040",
  },
  {
    name: "Praça das Flores - Produção de Espectáculos, Lda.",
    city: "Lisboa",
    country: "Portugal",
    address: "Rua Imprensa Nacional 36, 1250-126 Lisboa",
    notes: "Produtora com CAE 90040 — possível parceira para co-produções ou aluguer de salas.",
    region: "Sul",
    cae: "90010",
  },
  {
    name: "Smart Events - Produção de Espectáculos e Organização de Eventos, Lda.",
    city: "Lisboa",
    country: "Portugal",
    address: "Av. Infante D. Henrique 333, 5º - 62, 1800-282 Lisboa",
    notes: "Empresa especializada em eventos e espetáculos; potencial para parcerias e datas em circuito.",
    region: "Sul",
    cae: "90010",
  },
  {
    name: "Empresa Artística S.A",
    city: "Porto",
    country: "Portugal",
    address: "Rua Gonçalo Sampaio, Nº39, 6º, 4150-366 Porto",
    notes: "Empresa de espetáculos sediada no Porto com CAE 90040 — possível contacto para produções.",
    region: "Norte",
    cae: "90040",
  },
  {
    name: "Casino Fundanense S.A",
    city: "Fundão",
    country: "Portugal",
    address: "Praça do Município, 6230-338 Fundão",
    notes: "Operador regional com CAE 90040 — potencial para circuitos no interior.",
    region: "Centro",
    cae: "90040",
  },
  {
    name: "Cul.tur - Empresa Municipal de Cultura e Turismo de Santarém, Eem",
    city: "Santarém",
    country: "Portugal",
    notes: "Empresa municipal de cultura e turismo — possível espaço/gestão de eventos.",
    region: "Centro",
    cae: "90040",
  },
  {
    name: "Agência Roque - Produções e Agenciamento de Espectáculos, Lda",
    city: "Loures",
    country: "Portugal",
    notes: "Produtora e agenciamento de espetáculos — possível parceria para tours e eventos.",
    region: "Sul",
    cae: "90010",
  },
  {
    name: "Jovens Cantores de Lisboa - Animação Cultural, Crl",
    city: "Lisboa",
    country: "Portugal",
    notes: "Associação cultural de animação musical — potencial para colaborações educativas e concertos.",
    region: "Sul",
    cae: "93290",
  },
  {
    name: "Promodel, Lda",
    city: "Cascais",
    country: "Portugal",
    notes: "Empresa de produção e eventos — possível parceiro para shows e logística.",
    region: "Sul",
    cae: "90010",
  },
  {
    name: "Eurobowling Imobiliária e Técnica, Lda",
    city: "Viseu",
    country: "Portugal",
    notes: "Empresa técnica com experiência em eventos — verificar disponibilidade de espaço e infra.",
    region: "Centro",
    cae: "93290",
  },
  {
    name: "Share Your Views Lda",
    city: "Vila Nova de Cerveira",
    country: "Portugal",
    notes: "Produtora/empresa de eventos — potencial para showcases ou eventos corporativos.",
    region: "Norte",
    cae: "90010",
  },
  {
    name: "Chaves Viva - Associação Promotora Para O Ensino e Divulgação das Artes e Ofícios da Região Flaviense",
    city: "Chaves",
    country: "Portugal",
    notes: "Associação cultural — ideal para concertos educativos e atividades de difusão artística.",
    region: "Norte",
    cae: "93290",
  },
  {
    name: "Cinema Em Conversa - Cineclube da Maia",
    city: "Maia",
    country: "Portugal",
    equipment: "PA e projeção audiovisual (confirmar)",
    agreement: "(negociável)",
    notes: "Cineclube com programação cultural — possível para eventos híbridos ou showcases.",
    region: "Norte",
    cae: "93290",
  },
  {
    name: "Coniorquestra - Sociedade Musical, Lda",
    city: "Guimarães",
    country: "Portugal",
    notes: "Sociedade musical — possível parceria para concertos e ensaios abertos.",
    region: "Norte",
    cae: "93290",
  },
  {
    name: "Jorge Miguel Rodrigues, Unipessoal Lda",
    city: "Arganil",
    country: "Portugal",
    notes: "Produtor/empresa de eventos locais — verificar capacidade para shows intimistas.",
    region: "Centro",
    cae: "90010",
  },
  {
    name: "MEO Arena",
    city: "Lisboa",
    country: "Portugal",
    address: "Rossio dos Olivais, - Lisboa (Lisboa). Portugal",
    region: "Sul",
    cae: "90040",
  },
  {
    name: "Hard Club",
    city: "Porto",
    country: "Portugal",
    address: "Praça do Infante Dom Henrique, - Oporto (Porto). Portugal",
    region: "Norte",
    cae: "56302",
  },
  {
    name: "Praia do Aterro Norte",
    city: "Matosinhos",
    country: "Portugal",
    address: "Avda Liberdade, Leça da Palmeira, - Matosinhos (Porto). Portugal",
    region: "Norte",
    cae: "90040",
  },
  {
    name: "Praia da Duna do Caldeirão",
    city: "Caminha",
    country: "Portugal",
    address: "Âncora, - Caminha (Viana do Castelo). Portugal",
    region: "Norte",
    cae: "90040",
  },
  {
    name: "Antigo Parque de Campismo da Madalena",
    city: "Vila Nova de Gaia",
    country: "Portugal",
    address: "R. do Cerro 608, 4405-736 - Vila Nova de Gaia (Porto). Portugal",
    region: "Norte",
    cae: "90040",
  },
  {
    name: "Passeio Marítimo de Algés",
    city: "Oeiras",
    country: "Portugal",
    address: "Algés, - Oeiras (Lisboa). Portugal",
    region: "Sul",
    cae: "90040",
  },
  {
    name: "Parque Municipal de Quinta do Ega",
    city: "Vagos",
    country: "Portugal",
    address: ", - Vagos (Aveiro). Portugal",
    region: "Centro",
    cae: "90040",
  },
  {
    name: "Sagres Campo Pequeno",
    city: "Lisboa",
    country: "Portugal",
    address: "R. Chaby Pinheiro 11, - LISBOA (Lisboa). Portugal",
    region: "Sul",
    cae: "90040",
  },
  {
    name: "Forum Braga (former Altice Forum Braga)",
    city: "Braga",
    country: "Portugal",
    address: "Av. Dr. Francisco Pires Gonçalves, - Braga (Braga). Portugal",
    region: "Norte",
    cae: "90040",
  },
  {
    name: "Herdade do Cabeço da Flauta",
    city: "Sesimbra",
    country: "Portugal",
    address: "Meco, - Sesimbra (Setúbal). Portugal",
    region: "Sul",
    cae: "90040",
  },
  {
    name: "Herdade da Casa Branca, Zambujeira do Mar",
    city: "Odemira",
    country: "Portugal",
    address: "Herdade da Casa Branca, Zambujeira do Mar, - Odemira (Beja). Portugal",
    region: "Sul",
    cae: "90040",
  },
  {
    name: "Super Bock Arena - Pavilhao Rosa Mota",
    city: "Porto",
    country: "Portugal",
    address: "R. de Dom Manuel II, 4050-346 - OPORTO (Porto). Portugal",
    region: "Norte",
    cae: "90040",
  },
  {
    name: "Polideportivo de Pindelo dos Milagres",
    city: "Sao Pedro do Sul",
    country: "Portugal",
    address: "Rua da Liberdade, n° 20, Pindelo dos Milagres, - Sao Pedro do Sul (Viseu). Portugal",
    region: "Centro",
    cae: "90040",
  },
  {
    name: "Amador Artist's House | Louro",
    city: "Vila Nova de Famalicao",
    country: "Portugal",
    address: "R. Ernesto A. Carvalho, Louro, 4760-553 - Vila Nova de Famalicao (Braga). Portugal",
    region: "Norte",
    cae: "93290",
  },
  {
    name: "Coliseu dos Recreios",
    city: "Lisboa",
    country: "Portugal",
    address: "R. das Portas de Santo Antão, nº96, 1150-269 - Lisboa (Lisboa). Portugal",
    region: "Sul",
    cae: "90040",
  },
  {
    name: "LAV - Lisboa Ao Vivo",
    city: "Lisboa",
    country: "Portugal",
    address: "Avenida Marechal Gomes da Costa, 29 B, 1800-255 - Lisboa (Lisboa). Portugal",
    region: "Sul",
    cae: "90040",
  },
  {
    name: "Forte Santiago da Barra",
    city: "Viana do Castelo",
    country: "Portugal",
    address: "Castelo Santiago da Barra, 4900-360 - Viana do Castelo (Viana do Castelo). Portugal",
    region: "Norte",
    cae: "90040",
  },
  {
    name: "Sala Tejo - MEO Arena",
    city: "Lisboa",
    country: "Portugal",
    address: "Rossio dos Olivais, 1990, - Lisboa (Lisboa). Portugal",
    region: "Sul",
    cae: "90040",
  },
  {
    name: "Forum Braga - (Gran Auditorio)",
    city: "Braga",
    country: "Portugal",
    address: "Av. Dr. Francisco Pires Gonçalves, 4711-909 - Braga (Braga). Portugal",
    region: "Norte",
    cae: "90040",
  },
  {
    name: "Parque Empresarial Pindelo dos Milagres - S. Pedro do Sul",
    city: "San Pedro do Sul",
    country: "Portugal",
    address: "Pindelo dos Milagres - S. Pedro do Sul, - San Pedro do Sul (Viseu). Portugal",
    region: "Centro",
    cae: "90040",
  },
  {
    name: "City of Coimbra Stadium",
    city: "Coimbra",
    country: "Portugal",
    address: "R. Dom Manuel I, 3030-320 - Coímbra (Coimbra). Portugal",
    region: "Centro",
    cae: "90040",
  },
  {
    name: "Music Festival Vilar de Mouros",
    city: "Vilar de Mouros",
    country: "Portugal",
    address: "Vilar de Mouros, Portugal, - Vilar de Mouros (Viana do Castelo). Portugal",
    contactPhone: "+351937953054",
    region: "Norte",
    cae: "90040",
  },
  {
    name: "Cineteatro Capitólio",
    city: "Lisboa",
    country: "Portugal",
    address: "Parque Mayer, 1250-096 - Lisboa (Lisboa). Portugal",
    contactPhone: "+351211385340",
    region: "Sul",
    cae: "90040",
  },
  {
    name: "Recinto Laurus Nobilis Music",
    city: "Vila Nova de Famalicão",
    country: "Portugal",
    address: "Recinto Laurus Nobilis Music, 4760-553 - Vila Nova de Famalicão (Braga). Portugal",
    region: "Norte",
    cae: "90040",
  },
  {
    name: "Sala Incrível Almadense",
    city: "Almada",
    country: "Portugal",
    address: "Rua Capitão Leitão, nº3, 2800-158 - Almada (Setúbal). Portugal",
    url: "incrivelalmadense.pt/",
    region: "Sul",
    cae: "56302",
  },
  {
    name: "EXPONOR",
    city: "Porto",
    country: "Portugal",
    address: "Av. Dr. António Macedo,, 4454-515 - Oporto (Porto). Portugal",
    region: "Norte",
    cae: "90040",
  },
  {
    name: "Pabellón Multiusos Gondomar",
    city: "Gondomar",
    country: "Portugal",
    address: "Av. Multiusos, S. Cosme, Portugal, 4420-230 - Gondomar (Porto). Portugal",
    region: "Norte",
    cae: "90040",
  },
  {
    name: "Parque Urbano do Tejo e do Trancão",
    city: "Lisboa",
    country: "Portugal",
    address: "Passeio dos Heróis do Mar, sn,, 1990-059 - Lisboa (Lisboa). Portugal",
    region: "Sul",
    cae: "90040",
  },
  {
    name: "Coliseu of Porto (Coliseu Porto Ageas)",
    city: "Porto",
    country: "Portugal",
    address: "R. de Passos Manuel, nº 137, 4000-385 - Oporto (Porto). Portugal",
    contactPhone: "+351223394940",
    url: "www.coliseu.pt/",
    region: "Norte",
    cae: "90040",
  },
  {
    name: "Centro Cultural de Belém - Grande Auditório",
    city: "Lisboa",
    country: "Portugal",
    address: "Praça do Império, 1449-003 - Lisboa (Lisboa). Portugal",
    contactPhone: "+351213612400",
    region: "Sul",
    cae: "90040",
  },
  {
    name: "Centro Recreativo y Cultural Santo André - Mangualde",
    city: "Mangualde",
    country: "Portugal",
    address: "R. do Centro 2, 3530-239 - Mangualde (Viseu). Portugal",
    region: "Centro",
    cae: "93290",
  },
  {
    name: "Bourbon Room Oporto",
    city: "Porto",
    country: "Portugal",
    address: "António Carneiro 302, Armazém R, 4300-025 - Oporto (Porto). Portugal",
    region: "Norte",
    cae: "56302",
  },
  {
    name: "Parque de Campismo INATEL da Caparica",
    city: "S. João de Caparica",
    country: "Portugal",
    address: "Av. Afonso Albuquerque, 2825-450 - S. João de Caparica (Setúbal). Portugal",
    region: "Sul",
    cae: "90040",
  },
  {
    name: "Casa da Música - Sala Suggia",
    city: "Porto",
    country: "Portugal",
    address: "Av. da Boavista, 4149-071 - Oporto (Porto). Portugal",
    contactPhone: "+351220120220",
    region: "Norte",
    cae: "90040",
  },
  {
    name: "Jardins do Palácio Marquês de Pombal",
    city: "Oeiras",
    country: "Portugal",
    address: "Palácio do Marquês Pombal, 2780, - Oeiras (Lisboa). Portugal",
    contactPhone: "+351214408300",
    region: "Sul",
    cae: "90040",
  },
  {
    name: "Parque Desportivo Da Bela Vista",
    city: "São Pedro do Sul",
    country: "Portugal",
    address: "Cobertinha, Vila Maior, São Pedro do Sul, - Cobertinha, Vila Maior (Viseu). Portugal",
    region: "Centro",
    cae: "90040",
  },
  {
    name: "EXPOLIMA - Ponte de Lima Exhibition Park (Portugal)",
    city: "Ponte de Lima",
    country: "Portugal",
    address: ", - PONTE DE LIMA (Viana do Castelo). Portugal",
    region: "Norte",
    cae: "90040",
  },
  {
    name: "Sala MOUCO",
    city: "Porto",
    country: "Portugal",
    address: "Rua de Frei Heitor Pinto 65, 4300-252 - Oporto (Porto). Portugal",
    region: "Norte",
    cae: "56302",
  },
  {
    name: "Auditorio CCOP",
    city: "Porto",
    country: "Portugal",
    address: "Rua do Duque de Loulé 202, 4000-324 - Oporto (Porto). Portugal",
    region: "Norte",
    cae: "90040",
  },
  {
    name: "Music Station",
    city: "Lisboa",
    country: "Portugal",
    address: "Avenida Aquilino Ribeiro Machado 74 - próxima Estación de oriente, - LISBOA (Lisboa). Portugal",
    region: "Sul",
    cae: "56302",
  },
  {
    name: "Tivoli BBVA Theatre",
    city: "Lisboa",
    country: "Portugal",
    address: "Av. da Liberdade 182-188, 1250-146 - Lisboa (Lisboa). Portugal",
    region: "Sul",
    cae: "90040",
  },
  {
    name: "Leiría Municipal Stadium (Portugal)",
    city: "Leiria",
    country: "Portugal",
    address: "Arrabalde d'Aquém, 2400-137, 2400-137 - Leiría (Leiria). Portugal",
    region: "Centro",
    cae: "90040",
  },
  {
    name: "PINE CLIFFS RESORT (Albufeira)",
    city: "Albufeira",
    country: "Portugal",
    address: "Pine Cliffs Resort, Praia da Falesia,, - Albufeira (Faro). Portugal",
    region: "Sul",
    cae: "93293",
  },
  {
    name: "Oeiras Municipal Stadium",
    city: "Oeiras",
    country: "Portugal",
    address: "Rúa Coro de Santo Amaro de Oeiras, 12, 2780-416 - Oeiras (Lisboa). Portugal",
    region: "Sul",
    cae: "90040",
  },
  {
    name: "Sala REPÚBLICA DA MÚSICA",
    city: "Lisboa",
    country: "Portugal",
    address: "R. do Centro Cultural 29, 1700-106 - LISBOA (Lisboa). Portugal",
    region: "Sul",
    cae: "56302",
  },
  {
    name: "Pavilhão Carlos Lopes",
    city: "Lisboa",
    country: "Portugal",
    address: "Av. Sidónio Pais, nº16 (Parque Eduardo VII), 1070-051 - Lisboa (Lisboa). Portugal",
    contactPhone: "+351210312700",
    region: "Sul",
    cae: "90040",
  },
  {
    name: "Woodstock69 Rock Bar",
    city: "Porto",
    country: "Portugal",
    address: "R. São Roque da Lameira 1212, 4350-104 - Porto (Porto). Portugal",
    region: "Norte",
    cae: "56302",
  },
  {
    name: "Lisboa Camping",
    city: "Lisboa",
    country: "Portugal",
    address: "Estr. da Circunvalação, Lisboa, Portugal, 1400-061 - Lisboa (Lisboa). Portugal",
    contactPhone: "+351217628200",
    url: "www.lisboacamping.com/",
    region: "Sul",
    cae: "90040",
  },
  {
    name: "Heaven's Social Club",
    city: "Porto",
    country: "Portugal",
    address: "Av. de Fernão de Magalhães 118, Porto, Portugal, 4300-169 - Oporto (Porto). Portugal",
    contactPhone: "+351937583876",
    region: "Norte",
    cae: "56302",
  },
  {
    name: "COLISEU DE ELVAS (Portugal)",
    city: "Elvas",
    country: "Portugal",
    address: "Avenida de Badajoz, - ELVAS (Portalegre). Portugal",
    region: "Alentejo",
    cae: "90040",
  },
  {
    name: "Restelo Stadium",
    city: "Lisboa",
    country: "Portugal",
    address: "Praceta Torres do Restelo, 1449-015 - LISBOA (Lisboa). Portugal",
    region: "Sul",
    cae: "90040",
  },
  {
    name: "Associação Cultural e Recreativa Ermidense",
    city: "Tondela",
    country: "Portugal",
    address: "R. Associação 143, - Tondela (Viseu). Portugal",
    region: "Centro",
    cae: "93290",
  },
  {
    name: "Esmoriz Beach",
    city: "Ovar",
    country: "Portugal",
    address: "Esmoriz, - Ovar (Aveiro). Portugal",
    region: "Centro",
    cae: "90040",
  },
  {
    name: "Estádio da Luz",
    city: "Lisboa",
    country: "Portugal",
    address: "Av. Eusébio da Silva Ferreira, 1500-313 - LISBOA (Lisboa). Portugal",
    contactPhone: "+351932401904",
    region: "Sul",
    cae: "90040",
  },
  {
    name: "Orfeão de Viseu",
    city: "Viseu",
    country: "Portugal",
    address: "R. Serpa Pinto 156, 3500-219 - Viseu (Viseu). Portugal",
    region: "Centro",
    cae: "93290",
  },
  {
    name: "LX Factory",
    city: "Lisboa",
    country: "Portugal",
    address: "R. Rodrigues de Faria, 103 Piso 3, 1300-501 - Lisboa (Lisboa). Portugal",
    region: "Sul",
    cae: "93290",
  },
];






